jsondata = [
    {
   "created_at":"Fri Jan 08 23:51:14 +0000 2021",
   "id":1347692371224399872,
   "id_str":"1347692371224399872",
   "full_text":"RT @smkoneru: Happy and proud to have volunteered for the final trials for #Covaxin of @BharatBiotech ..Got my shot. \n\nKudos to the team fo\u2026",
   "truncated":false,
   "display_text_range":[
      0,
      140
   ],
   "entities":{
      "hashtags":[
         {
            "text":"Covaxin",
            "indices":[
               75,
               83
            ]
         }
      ],
      "symbols":[
         
      ],
      "user_mentions":[
         {
            "screen_name":"smkoneru",
            "name":"Mahesh Koneru",
            "id":137183148,
            "id_str":"137183148",
            "indices":[
               3,
               12
            ]
         },
         {
            "screen_name":"BharatBiotech",
            "name":"BharatBiotech",
            "id":2590932906,
            "id_str":"2590932906",
            "indices":[
               87,
               101
            ]
         }
      ],
      "urls":[
         
      ]
   },
   "metadata":{
      "iso_language_code":"en",
      "result_type":"recent"
   },
   "source":"<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
   "in_reply_to_status_id":null,
   "in_reply_to_status_id_str":null,
   "in_reply_to_user_id":null,
   "in_reply_to_user_id_str":null,
   "in_reply_to_screen_name":null,
   "user":{
      "id":470098874,
      "id_str":"470098874",
      "name":"g.sampathkumar",
      "screen_name":"ntrsampath",
      "location":"Vijayawada",
      "description":"\u1d05\u026a\u1d07\u029c\u1d00\u0280\u1d05 \ua730\u1d00\u0274 \u1d0f\ua730  \ud83c\udd3d\ud83c\udd43\ud83c\udd41\ud83d\udc2f @tarak9999,\n\ud835\ude41\ud835\ude56\ud835\ude6b\ud835\ude64\ud835\ude67\ud835\ude5e\ud835\ude69\ud835\ude5a \ud835\ude65\ud835\ude64\ud835\ude61\ud835\ude5e\ud835\ude69\ud835\ude5e\ud835\ude58\ud835\ude5e\ud835\ude56\ud835\ude63 @ncbn \ud83c\udd83\ud83c\udd73\ud83c\udd7f \ud83d\udc9b#TDPTwitter\u270c,\ud835\ude43\ud835\ude5e\ud835\ude4f\ud835\ude62\ud835\ude56\ud835\ude49  @ImRo45 \ud83d\udc99 @urstrulymahesh @MsKajalAggarwal",
      "url":null,
      "entities":{
         "description":{
            "urls":[
               
            ]
         }
      },
      "protected":false,
      "followers_count":91,
      "friends_count":450,
      "listed_count":0,
      "created_at":"Sat Jan 21 09:59:18 +0000 2012",
      "favourites_count":6955,
      "utc_offset":null,
      "time_zone":null,
      "geo_enabled":false,
      "verified":false,
      "statuses_count":7068,
      "lang":null,
      "contributors_enabled":false,
      "is_translator":false,
      "is_translation_enabled":false,
      "profile_background_color":"C0DEED",
      "profile_background_image_url":"http://abs.twimg.com/images/themes/theme1/bg.png",
      "profile_background_image_url_https":"https://abs.twimg.com/images/themes/theme1/bg.png",
      "profile_background_tile":false,
      "profile_image_url":"http://pbs.twimg.com/profile_images/1293175800619966466/ZQlfDrbc_normal.jpg",
      "profile_image_url_https":"https://pbs.twimg.com/profile_images/1293175800619966466/ZQlfDrbc_normal.jpg",
      "profile_banner_url":"https://pbs.twimg.com/profile_banners/470098874/1599361158",
      "profile_link_color":"1DA1F2",
      "profile_sidebar_border_color":"C0DEED",
      "profile_sidebar_fill_color":"DDEEF6",
      "profile_text_color":"333333",
      "profile_use_background_image":true,
      "has_extended_profile":true,
      "default_profile":true,
      "default_profile_image":false,
      "following":false,
      "follow_request_sent":false,
      "notifications":false,
      "translator_type":"none"
   },
   "geo":null,
   "coordinates":null,
   "place":null,
   "contributors":null,
   "retweeted_status":{
      "created_at":"Wed Jan 06 04:57:11 +0000 2021",
      "id":1346682200566054912,
      "id_str":"1346682200566054912",
      "full_text":"Happy and proud to have volunteered for the final trials for #Covaxin of @BharatBiotech ..Got my shot. \n\nKudos to the team for the breakthrough.. \ud83d\ude4f\ud83c\udffb\ud83d\ude4f\ud83c\udffb\ud83d\ude4f\ud83c\udffb #MadeInIndia",
      "truncated":false,
      "display_text_range":[
         0,
         165
      ],
      "entities":{
         "hashtags":[
            {
               "text":"Covaxin",
               "indices":[
                  61,
                  69
               ]
            },
            {
               "text":"MadeInIndia",
               "indices":[
                  153,
                  165
               ]
            }
         ],
         "symbols":[
            
         ],
         "user_mentions":[
            {
               "screen_name":"BharatBiotech",
               "name":"BharatBiotech",
               "id":2590932906,
               "id_str":"2590932906",
               "indices":[
                  73,
                  87
               ]
            }
         ],
         "urls":[
            
         ]
      },
      "metadata":{
         "iso_language_code":"en",
         "result_type":"recent"
      },
      "source":"<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
      "in_reply_to_status_id":null,
      "in_reply_to_status_id_str":null,
      "in_reply_to_user_id":null,
      "in_reply_to_user_id_str":null,
      "in_reply_to_screen_name":null,
      "user":{
         "id":137183148,
         "id_str":"137183148",
         "name":"Mahesh Koneru",
         "screen_name":"smkoneru",
         "location":"Hyderabad, India",
         "description":"PR for @tarak9999,@nandamurikalyan,@NTRArtsOfficial, @baahubalimovie. Producer of #118Movie #MissIndia @EastCoastPrdns . Telugu Distributor  #Bigil #Master",
         "url":null,
         "entities":{
            "description":{
               "urls":[
                  
               ]
            }
         },
         "protected":false,
         "followers_count":512618,
         "friends_count":748,
         "listed_count":159,
         "created_at":"Mon Apr 26 01:57:39 +0000 2010",
         "favourites_count":912,
         "utc_offset":null,
         "time_zone":null,
         "geo_enabled":true,
         "verified":true,
         "statuses_count":16366,
         "lang":null,
         "contributors_enabled":false,
         "is_translator":false,
         "is_translation_enabled":false,
         "profile_background_color":"131516",
         "profile_background_image_url":"http://abs.twimg.com/images/themes/theme14/bg.gif",
         "profile_background_image_url_https":"https://abs.twimg.com/images/themes/theme14/bg.gif",
         "profile_background_tile":false,
         "profile_image_url":"http://pbs.twimg.com/profile_images/1279795526909587457/hQUQLCaD_normal.jpg",
         "profile_image_url_https":"https://pbs.twimg.com/profile_images/1279795526909587457/hQUQLCaD_normal.jpg",
         "profile_banner_url":"https://pbs.twimg.com/profile_banners/137183148/1551106537",
         "profile_link_color":"009999",
         "profile_sidebar_border_color":"FFFFFF",
         "profile_sidebar_fill_color":"EFEFEF",
         "profile_text_color":"333333",
         "profile_use_background_image":true,
         "has_extended_profile":true,
         "default_profile":false,
         "default_profile_image":false,
         "following":false,
         "follow_request_sent":false,
         "notifications":false,
         "translator_type":"none"
      },
      "geo":null,
      "coordinates":null,
      "place":null,
      "contributors":null,
      "is_quote_status":false,
      "retweet_count":374,
      "favorite_count":3417,
      "favorited":false,
      "retweeted":false,
      "lang":"en"
   },
   "is_quote_status":false,
   "retweet_count":374,
   "favorite_count":0,
   "favorited":false,
   "retweeted":false,
   "lang":"en"
}]